- hosts: localhost
#  strategy: debug
  vars:
   host: "192.168.115.128"
   username: "admin"
   password: "adminpasswd"
   vdom: "root"
  tasks:
  - name: Upload python module wrkaround when pip is not an option.
    copy: src=library/fortiosapi.py dest=/usr/local/lib/python2.7/dist-packages/fortiosapi.py
  - name: Set static route on the fortigate
    fortiosconfig:
     action: "set"
     host:  "{{  host }}"  
     username: "{{  username}}"  
     password: "{{ password }}"  
     vdom:  "{{  vdom }}"  
     config: "router static"
     config_parameters:
       seq-num: "8"
       dst: "10.10.32.0 255.255.255.0"
       device: "port2"
       gateway: "192.168.40.252"
  - name: add firewall address 
    fortiosconfig:
     config: "firewall address"
     action: "set"
     host:  "{{ host }}"  
     username: "{{ username }}"  
     password: "{{ password }}"  
     vdom:  "{{  vdom }}"
     config_parameters:
       wildcard-fqdn: "*.libertyglobal.com"
       name: "lb-ansible"
       type: "wildcard-fqdn"
  - name: add  firewall policy
    fortiosconfig:
     config: "firewall policy"
     action: "set"
     host:  "{{ host }}"  
     username: "{{ username }}"  
     password: "{{ password }}"  
     vdom:  "{{  vdom }}"
     config_parameters:
        policyid: "66"
        name: "ansible"
        json:
          policyid: "66"
          name: "ansible"
          action: "accept"
          srcintf: [ {"name": "port1"} ] 
          dstintf: [{"name":"port2"} ] 
          srcaddr: [{"name":"all"} ] 
          dstaddr: [{"name":"all"}] 
          schedule: "always" 
          service:  [{"name":"HTTPS"}] 
          logtraffic: "all"  
  - name: fortimanager management settings
    fortiosconfig:
     config: "system central-management"
     action: "put"
     host:  "{{ host }}"  
     username: "{{ username }}"  
     password: "{{ password }}"
     vdom: "global"
     config_parameters:
        "type": "fortimanager"
        fmg: "10.210.67.18"
