- hosts: localhost
#  strategy: debug
  vars:
#   host: "192.168.122.70"
   host:  "192.168.115.128"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
# If you manage python pip externaly you don't need that version is
# here to ensure update/downgrade if needed (optional)
#  - pip: 
#     name: fortiosapi
#     version: 0.9.5
  - name: Set static route on the fortigate
    fortios_cmdb_set:
     host:  "{{  host }}"  
     username: "{{  username}}"  
     password: "{{ password }}"  
     vdom:  "{{  vdom }}"  
     endpoint: "router static"
     config_parameters:
       seq-num: "8"
       dst: "10.10.32.0 255.255.255.0"
       device: "port2"
       gateway: "192.168.40.252"
  - name: add multiple firewall address 
    fortios_cmdb_set:
     endpoint: "firewall address"
     host:  "{{ host }}"  
     username: "{{ username }}"  
     password: "{{ password }}"  
     vdom:  "{{  vdom }}"
     config_parameters:
       wildcard-fqdn: "*.{{ item }}"
       name: "all.{{ item }}"
       type: "wildcard-fqdn"
    with_items:
       - "fortinet.com"
       - "acme.org"
  - name:   firewall policy
    fortios_cmdb_set:
     endpoint: "firewall policy"
     host:  "{{ host }}"  
     username: "{{ username }}"  
     password: "{{ password }}"  
     vdom:  "{{  vdom }}"
     config_parameters:
        policyid: "66"
        name: "ansible"
        json:
          policyid: "66"
          name: "ansible"
          action: "accept"
          srcintf: [ {"name": "port1"} ] 
          dstintf: [{"name":"port2"} ] 
          srcaddr: [{"name":"all"} ] 
          dstaddr: [{"name":"all"}] 
          schedule: "always" 
          service:  [{"name":"HTTPS"}] 
          logtraffic: "all"  
