- hosts: localhost
  vars:
   auth_url: "http://10.210.8.17/identity/"
   username: "admin"
   password: "password"
   tenant_name: "admin"
   region_name: "RegionOne"
   project_domain: "default"
   user_domain: "default"
  tasks:
  - name: Instantiate FortiGate in OpenStack
    os_server:
     auth_url:  "{{ auth_url }}"
     username: "{{ username }}"
     password: "{{ password }}"
     tenant_name: "{{ tenant_name }}"
     region_name: "{{ region_name }}"
     project_domain: "{{ project_domain }}"
     user_domain: "{{ user_domain }}"
     name: "MyFortigate"
     state: "present"
     image: "fortigate"
     volume_size: "1"
     flavor: "m1.small"
     ssh_key: "t1"
     availability_zone: "zone1"
     networks:
      - net-name: "netA"
      - net-name: "netB"
     userdata: "file1.txt"
     license: "license.lic"
